---
train: "Jets_EMC_pp_MC"
number: 2461
dataset: "LHC18b8"
aliphysics_tag: "vAN-20201214_ROOT6-1"
alien_output_dir:
    child_2:
        name: "woSDD"
        stage_to_download: "run_by_run"
    child_3:
        name: "FAST"
        stage_to_download: "run_by_run"
status: |
    "Recursive splittings for R=0.2 jet splittings with pythia. Requires run-by-run output to get"
    " the pt hard scaling correct."
