---
train: "Jets_EMC_PbPb"
number: 6667
dataset: "LHC18{q,r}"
pass: 3
AOD: 242
aliphysics_tag: "v5-09-57-01_ROOT6-1"
embedded_dataset: "LHC20g4"
pt_hard_bin: 18
alien_output_info:
    child_1:
        name: "LHC18q"
        stage_to_download: "manual"
        manual:
            295676: "single_run_manual"
            295755: "merged"
            295822: "merged"
            295913: "merged"
            296065: "merged"
            296068: "merged"
            296132: "merged"
            296133: "merged"
            296244: "merged"
            296270: "merged"
            296377: "merged"
            296414: "merged"
            296433: "merged"
            296550: "single_run_manual"
    child_2:
        name: "LHC18r"
        stage_to_download: "manual"
        manual:
            296694: "merged"
            296894: "merged"
            296899: "merged"
            296903: "merged"
            296934: "merged"
            297193: "merged"
            297218: "merged"
            297221: "merged"
            297380: "merged"
            297415: "merged"
            297446: "merged"
            297450: "merged"
            297544: "merged"
            297590: "single_run_manual"
status: |
    "Substructure embedding semi-central, record all splittings. Double counting cut applied (with fix),"
    " updated to pass 3, Rmax=0.25 nominal. The grid started tanked at the end of this train, which"
    " increased the failure rate (and therefore made merging more difficult)."
