---
train: "Jets_EMC_pp"
trainNumber: 1789
production: "LHC17q"
alienOutputDir:
    FAST: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_pp/1789_20200217-2113_child_1/merge"
    woSDD: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_pp/1789_20200217-2113_child_2/merge"
status: |
    "First pass at R=0.4 jet splittings on pp data with recursive splittings recorded."
