---
train: "Jets_EMC_pp"
number: 1789
dataset: "LHC17q"
aliphysics_tag: "vAN-20200217_ROOT6-1"
alien_output_info:
    child_1:
        name: "FAST"
        stage_to_download: "merged"
    child_2:
        name: "woSDD"
        stage_to_download: "merged"
status: |
    "First pass at R=0.4 jet splittings on pp data with recursive splittings recorded."
