---
train: "Jets_EMC_PbPb"
number: 6696
dataset: "LHC18{q,r}"
pass: 3
AOD: 242
aliphysics_tag: "v5-09-57-01_ROOT6-1"
embedded_dataset: "LHC20g4"
pt_hard_bin: 2
alien_output_info:
    child_1:
        name: "LHC18q"
        stage_to_download: "merged"
    child_2:
        name: "LHC18r"
        stage_to_download: "merged"
status: |
    "Substructure embedding semi-central, record all splittings. Double counting cut applied (with fix),"
    " updated to pass 3, tracking efficiency systematic."
