---
train: "Jets_EMC_PbPb"
number: 6325
dataset: "LHC18{q,r}"
aliphysics_tag: "vAN-20200720_ROOT6-1"
embedded_dataset: "LHC19f4"
pt_hard_bin: 10
alien_output_info:
    child_1:
        name: "LHC18r"
        stage_to_download: "Stage_5"
    child_2:
        name: "LHC18q"
        stage_to_download: "Stage_5"
status: |
    "Substructure embedding semi-central, record all splittings. Double counting cut applied (with fix),"
    " Rmax=0.6 systematic."
