---
train: "Jets_EMC_PbPb"
number: 5537
dataset: "LHC18{q,r}"
aliphysics_tag: "vAN-20200221_ROOT6-1"
alienOutputDir:
    lhc18r: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/5537_20200223-1249_child_1/merge"
    lhc18q: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/5537_20200223-1249_child_2/merge"
status: |
    "Recording all recursive splittings. Required manual merging because Stage_5 failed."
