---
train: "Jets_EMC_PbPb"
number: 5988
dataset: "LHC18{q,r}"
aliphysics_tag: "vAN-20200605_ROOT6-1"
embedded_dataset: "LHC19f4"
pt_hard_bin: 1
alien_output_info:
    child_1:
        name: "LHC18r"
        stage_to_download: "merged"
    child_2:
        name: "LHC18q"
        stage_to_download: "merged"
status: |
    "Simplified task which recorded the leading kt z > 0.2 splittings in embedded pythia. This allows for a cross check with our more"
    " complicated task which records all splittings. Nominal settings. Doesn't include the double counting cut, so it needs to be applied offline."
