# Shared parameters
_prefix_branches_standard: &prefix_branches
    - "{prefix}.fJetPt"
    - "{prefix}.fJetConstituents.fPt"
    - "{prefix}.fJetConstituents.fEta"
    - "{prefix}.fJetConstituents.fPhi"
    - "{prefix}.fJetConstituents.fID"
    - "{prefix}.fJetSplittings.fKt"
    - "{prefix}.fJetSplittings.fDeltaR"
    - "{prefix}.fJetSplittings.fZ"
    - "{prefix}.fJetSplittings.fParentIndex"
    - "{prefix}.fSubjets.fPartOfIterativeSplitting"
    - "{prefix}.fSubjets.fSplittingNodeIndex"
    - "{prefix}.fSubjets.fConstituentIndices"

available_datasets:
    LHC18qr: &LHC18qr
        name: "LHC18qr_5863"
        # yamllint disable-line rule:line-length
        tree_name: "AliAnalysisTaskJetDynamicalGrooming_Jet_AKTChargedR040_tracks_pT0150_E_schemeConstSub_RawTree_Data_ConstSub_Incl"
        # A map to potentially rename the branch prefix.
        prefixes:
            data: "data"
        # Branches which don't contain a prefix
        branches: []
        # Branches which contain a prefix. The prefix will be filled for each prefix defined above.
        prefix_branches: *prefix_branches
        jet_R: 0.4
        files:
            - "trains/PbPb/5863/AnalysisResults.*.repaired.root"
    LHC18qr_Rmax06:
        name: "LHC18qr_5862"
        # yamllint disable-line rule:line-length
        tree_name: "AliAnalysisTaskJetDynamicalGrooming_Jet_AKTChargedR040_tracks_pT0150_E_schemeConstSub_RawTree_Data_ConstSub_Incl"
        # A map to potentially rename the branch prefix.
        prefixes:
            data: "data"
        # Branches which don't contain a prefix
        branches: []
        # Branches which contain a prefix. The prefix will be filled for each prefix defined above.
        prefix_branches: *prefix_branches
        jet_R: 0.4
        files:
            - "trains/PbPb/5862/AnalysisResults.*.repaired.root"
    LHC19f4_embedded_into_LHC18qr_5966_5985: &LHC19f4_embedded_into_LHC18qr
        name: "LHC19f4_embedded_into_LHC18qr_5966_5985"
        # yamllint disable-line rule:line-length
        tree_name: "AliAnalysisTaskJetDynamicalGrooming_hybridLevelJets_AKTChargedR040_tracks_pT0150_E_schemeConstSub_RawTree_EventSub_Incl"
        # A map to potentially rename the branch prefix.
        prefixes:
            data: "hybrid"
            matched: "true"
            detLevel: "det_level"
        # Branches which don't contain a prefix
        branches: []
        # Branches which contain a prefix. The prefix will be filled for each prefix defined above.
        prefix_branches: *prefix_branches
        jet_R: 0.4
        scale_factors:
            1: 16.0695
            2: 4.60776
            3: 2.14894
            4: 0.781811
            5: 0.26462
            6: 0.0975008
            7: 0.0292782
            8: 0.00988435
            9: 0.0040435
            10: 0.00135313
            11: 0.000529795
            12: 0.000188235
            13: 9.22016e-05
            14: 4.29112e-05
            15: 2.09133e-05
            16: 1.06058e-05
            17: 5.74855e-06
            18: 3.0036e-06
            19: 1.61604e-06
            20: 2.0978e-06
        files:
            - "trains/embedPythia/5966/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5967/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5968/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5969/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5970/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5971/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5972/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5973/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5974/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5975/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5976/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5977/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5978/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5979/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5980/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5981/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5982/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5983/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5984/AnalysisResults.*.repaired.root"
            - "trains/embedPythia/5985/AnalysisResults.*.repaired.root"

execution:
    embedPythia:
        dataset: *LHC19f4_embedded_into_LHC18qr
    PbPb:
        dataset: *LHC18qr

