---
train: "Jets_EMC_PbPb"
number: 5740
dataset: "LHC18{q,r}"
aliphysics_tag: "vAN-20200421_ROOT6-1"
alienOutputDir:
    lhc18r: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/5740_20200507-1604_child_1/merge"
    lhc18q: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/5740_20200507-1604_child_2/merge"
status: |
    "Recorded all recursive splittings in data. Rmax=0.6 systematic. Problem with extracted consitutnets - don't use."
