---
train: "Jets_EMC_pp_MC"
number: 2110
dataset: "LHC18b8"
aliphysics_tag: "vAN-20200222_ROOT6-1"
alien_output_dir:
    child_2:
        name: "woSDD"
        stage_to_download: "run_by_run"
    child_3:
        name: "FAST"
        stage_to_download: "run_by_run"
status: |
    "First pass at R=0.4 jet splittings on pythia with recursive splittings recorded."
    " Due to an apparently grid issue, the FAST child didn't merge successfully. Some fraction of the"
    " files made it through stage 5, but some the rest failed at stage 1. Those that failed at stage 1"
    " were manually merged (note that stage 1 xml stored in the directory was the input of the files that"
    " were merged). There were further issues with the woSDD due to zlib chunk corruption in at least one file."
    " All of this was resolved by downloading all of the Stage_1 files for woSDD, and then not merging them."
    " This seemed to yield _substantially_ more data."
    " On 8 April 2020, now that I understand and can address the corruption, I merge the woSDD files into 5 larger"
    " files, and then split and repaired the entire dataset."
    " Update later in 2020: Use Markus' or my script to download run-by-run appropriately for right scaling!"
