---
train: "Jets_EMC_PbPb"
number: 5983
dataset: "LHC18{q,r}"
aliphysics_tag: "vAN-20200513_ROOT6-1"
embedded_dataset: "LHC19f4"
pt_hard_bin: 18
alien_output_info:
    child_1:
        name: "LHC18r"
        stage_to_download: "manual"
        manual:
            # NOTE: The run numbers don't match up with the output directories in MonALISA. Probably due to a bug.
            #       So I matched their merging state up to the output directories.
            297544: "merged"
            297442: "Stage_5"
            297441: "Stage_5"
            297414: "Stage_5"
            297379: "merged"
            297315: "merged"
            297222: "Stage_5"
            296941: "Stage_5"
            296935: "merged"
            296934: "Stage_5"
            296852: "merged"
            296850: "Stage_5"
            296690: "Stage_5"
            297481: "merged"
    child_2:
        name: "LHC18q"
        stage_to_download: "Stage_5"
status: |
    "Substructure embedding semi-central, record all splittings. Double counting cut applied (with fix),"
    " Rmax=0.25 nominal."
