---
train: "Jets_EMC_PbPb"
number: 6345
dataset: "LHC18{q,r}"
aliphysics_tag: "vAN-20200720_ROOT6-1"
embedded_dataset: "LHC19f4"
pt_hard_bin: 8
alien_output_info:
    child_1:
        name: "LHC18r"
        stage_to_download: "manual"
        manual:
            # NOTE: The run numbers don't match up with the output directories in MonALISA. Probably due to a bug.
            #       So I matched their merging state up to the output directories.
            296690: "merged"
            296850: "merged"
            296852: "merged"
            296934: "merged"
            296935: "merged"
            296941: "merged"
            297222: "merged"
            297315: "merged"
            297379: "single_run_manual"
            297414: "merged"
            297441: "merged"
            297442: "merged"
            297481: "merged"
            297544: "merged"
    child_2:
        name: "LHC18q"
        stage_to_download: "merged"
status: |
    "Substructure embedding central hardest kt iterative splittings. Double counting cut applied (with fix),"
    " Rmax=0.25 nominal."
