---
train: "Jets_EMC_PbPb"
number: 6688
dataset: "LHC18{q,r}"
pass: 3
AOD: 242
aliphysics_tag: "v5-09-57-01_ROOT6-1"
embedded_dataset: "LHC20g4"
pt_hard_bin: 15
alien_output_info:
    child_1:
        name: "LHC18q"
        stage_to_download: "manual"
        manual:
            295676: "merged"
            295755: "merged"
            295822: "Stage_5"
            295913: "merged"
            296065: "merged"
            296068: "Stage_5"
            296132: "merged"
            296133: "merged"
            296244: "merged"
            296270: "merged"
            296377: "merged"
            296414: "merged"
            296433: "merged"
            296550: "merged"
    child_2:
        name: "LHC18r"
        stage_to_download: "manual"
        manual:
            000296694: "merged"
            000296894: "merged"
            000296899: "merged"
            000296903: "merged"
            000296934: "Stage_5"
            000297193: "merged"
            000297218: "merged"
            000297221: "merged"
            000297380: "merged"
            000297415: "merged"
            000297446: "merged"
            000297450: "merged"
            000297544: "merged"
            000297590: "merged"
status: |
    "Substructure embedding semi-central, record all splittings. Double counting cut applied (with fix),"
    " updated to pass 3, Rmax=0.05 systematic."
