---
train: "Jets_EMC_PbPb"
number: 6673
dataset: "LHC18{q,r}"
pass: 3
AOD: 242
aliphysics_tag: "vAN-20210126_ROOT6-1"
alien_output_info:
    child_1:
        name: "LHC18q"
        stage_to_download: "merged"
    child_2:
        name: "LHC18r"
        stage_to_download: "merged"
status: |
    "Recorded all recursive splittings in data. Updated to pass 3, Rmax=0.70 systematic."
    " Fix for substracted constituents."
